[package]
name = "enrust"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
divan = "0.1"

[[bench]]
name = "chess_benchmarks"
harness = false

[[bench]]
name = "perft_benchmarks"
harness = false